sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
   - 2.10.4
   - 2.11.6

jdk:
   - oraclejdk7

sbt_args: -no-colors -J-Xss2m

script: sbt ++$TRAVIS_SCALA_VERSION -Dsbt.log.noformat=true assembly test

notifications:
  email:
    - seth.yates@krux.com
    - kxie@krux.com
    - ysalomon@krux.com

after_success:
   - >
        if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
            sbt ghpagesPushSite
            sbt ++$TRAVIS_SCALA_VERSION 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USERNAME"), System.getenv("SONATYPE_PASSWORD"))' publish
        fi

